version: "3"

services:
  jenkins:
    image: jenkins:2.7.2
    volumes:
      - jenkins-vol:/var/jenkins_home
    environment:
      - JENKINS_OPTS=--prefix=/
    ports:
      - 8080:8080
      - 50000:50000
    deploy:
      placement:
        constraints: [node.labels.jenkins_vol == true]
        # Todo: docker node update --label-add jenkins_vol=true node1
    networks:
      - jenkins-stack

volumes:
  jenkins-vol:

networks:
  jenkins-stack: